[project]
name = "build-nanogpt2"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "jupyter>=1.1.1",
    "matplotlib>=3.10.3",
    "numpy<2",
    "tqdm>=4.67.1",
    "transformers>=4.53.0",
]
